config/routes.rb
Datachimp::Application.routes.draw do
  resources :credit_cards, only: [:index, :new, :create, :destroy]
  resources :bank_accounts, only: [:index, :new, :create, :destroy]
  resources :contest_followings, only: [:index, :create, :destroy]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "contests#index"
  resources :pending_contests, only: [:index]
  resources :past_contests, only: [:index]

  resources :contests do
    resources :entries do
      member do
        post :rate
        delete :remove
        get :pick_winning
      end
      resources :feedbacks, only: [:new, :create, :edit, :update, :destroy]
    end
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  attr_accessible :contest, :data_set_url, :description, :user

  ajaxful_rateable stars: 5, dimensions: [:quality, :amount, :speed], cache_column: :rating

  belongs_to :user
  belongs_to :contest

  has_many :feedbacks

  validates :contest, :user, :description, :data_set_url, presence: true

  validates :user_id, uniqueness: {scope: :contest_id, message: "cannot enter contest twice"}

  validate :owner_has_account, :contest_not_expired, :own_contest, :on => :create

  after_create :follow_contest

  scope :active, where(removed: false)

  def remove
    self.removed = true
    save
  end

  def headline
    "#{user.email} - #{description.try(:[], 0..10)}"
  end

  private

  def own_contest
    errors.add(:base, "Cannot enter your own contest.") if contest.try(:user) == user
  end

  def contest_not_expired
    errors.add(:base, "The contest is expired.") if contest.try(:expired?)
  end

  def owner_has_account
    errors.add(:base, "Owner must have an account to create a new entry.") unless user.balanced_account_uri.present?
  end

  def follow_contest
    user.follow(contest)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_filter :find_contest
  before_filter :find_entry, except: [:index, :new, :create]
  before_filter :verify_ownership, only: [:edit, :update, :destroy]
  before_filter :verify_contest_ownership, only: [:rate, :remove]
  before_filter :verify_submission_permission, only: [:new]
  before_filter :verify_view_permission, only: [:show]
  # GET /entries
  # GET /entries.json
  def index
    @entries = @contest.entries.active

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @entries }
    end
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
    @entry = Entry.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/new
  # GET /entries/new.json
  def new
    @entry = Entry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @entry }
    end
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = @contest.entries.new(params[:entry].merge(user: current_user))

    respond_to do |format|
      if @entry.save
        format.html { redirect_to contest_entry_url(@contest, @entry), notice: 'Entry was successfully created.' }
        format.json { render json: @entry, status: :created, location: @entry }
      else
        format.html { render action: "new" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /entries/1
  # PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update_attributes(params[:entry])
        format.html { redirect_to contest_entry_url(@contest, @entry), notice: 'Entry was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  def rate
    @entry.rate(params[:stars], current_user, params[:dimension])
    respond_to do |format|
      format.html { redirect_to contest_entry_url(@contest, @entry) }
      format.js { render layout: false }
    end
  end

  def remove
    @entry.remove
    redirect_to contest_url(@contest)
  end

  def pick_winning
    if @entry.user.credit_cards.any? && @contest.pick_winner(@entry)
      flash[:notice] = "Prize awarded to winner"
    else
      flash[:error] = "Error picking winner"
    end
    redirect_to contest_entry_url(@contest, @entry)
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to contest_entries_url(@contest) }
      format.json { head :no_content }
    end
  end

  private
  def find_contest
    @contest = Contest.find(params[:contest_id])
  end

  def find_entry
    @entry = Entry.find(params[:id])
  end

  def verify_ownership
    unless current_user == @entry.user
      redirect_to root_path
      return
    end
  end

  def verify_contest_ownership
    unless current_user == @contest.user
      redirect_to root_path
      return
    end
  end

  def verify_submission_permission
    if current_user == @contest.user
      redirect_to contest_path(@contest), notice: 'Cannot enter your own contest.'
    elsif @contest.entries.exists?(user_id: current_user.id)
      redirect_to contest_path(@contest), notice: 'You cannot enter contest twice.'
    end
  end

  def verify_view_permission
    unless current_user == @contest.user || current_user == @entry.user
      redirect_to contest_path(@contest), notice: 'You cannot view other submitted entries'
    end
  end
end

app/views/entries/_entry.html.haml
.entry
  - if current_user && current_user.own?(entry.contest)
    .user
      = link_to entry.user.name, contest_entry_path(entry.contest, entry)
    .url
      = entry.data_set_url
    %div.rating{id: "entry-rating-#{entry.id}"}
      = entry_rating(entry)
    .pick-winner
      = link_to "Pick as winner", pick_winning_contest_entry_path(entry.contest, entry), confirm: "Are you sure?"
    .remove
      = link_to "Remove this entry", remove_contest_entry_path(entry.contest, entry), method: :delete, confirm: "Are you sure?"
    .feedbacks
      = pluralize(entry.feedbacks.count, "feedback")
  - else
    .user= entry.user.name

app/views/entries/_form.html.haml
- content_for :extra_js do
  = filepicker_js_include_tag

= form_for [@contest, @entry] do |f|
  - if @entry.errors.any?
    #error_explanation
      %h2= "#{pluralize(@entry.errors.count, "error")} prohibited this entry from being saved:"
      %ul
        - @entry.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :data_set_url
    = f.filepicker_field :data_set_url
  .actions
    = f.submit 'Save'

app/views/entries/edit.html.haml
%h1 Editing entry

= render 'form'

= link_to 'Show', contest_entry_path(@contest, @entry)
\|
= link_to 'Back', contest_entries_path(@contest)

app/views/entries/index.html.haml
%h1 Listing entries

%table
  %tr
    %th Contest
    %th User
    %th Description
    %th Data set url
    %th
    %th
    %th

  - @entries.each do |entry|
    %tr
      %td= entry.contest_id
      %td= entry.user_id
      %td= entry.description
      %td= entry.data_set_url
      %td= link_to 'Show', contest_entry_path(@contest, entry)
      %td= link_to 'Edit', edit_contest_entry_path(@contest, entry)
      %td= link_to 'Destroy', contest_entry_path(@contest, entry), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Entry', new_contest_entry_path(@contest)

app/views/entries/new.html.haml
%h1 New entry

= render 'form'

= link_to 'Back', contest_entries_path(@contest)

app/views/entries/rate.js.haml
:plain
  $("#entry-rating-#{@entry.id}").html("#{escape_javascript entry_rating(@entry, wrap: false)}")

app/views/entries/show.html.haml
%p#notice= notice

%p
  %b Contest:
  = link_to(@entry.contest.name, @entry.contest)
%p
  %b User:
  = @entry.user.name
%p
  %b Description:
  = @entry.description
%p
  %b Data set url:
  = @entry.data_set_url
%p
  %b Rating
%div{id: "entry-rating-#{@entry.id}"}
  = entry_rating(@entry)

= link_to 'Edit', edit_contest_entry_path(@contest, @entry)
\|
= link_to 'Back', contest_entries_path(@contest)

%h2 Feedbacks
%p
  = link_to "Add feedback", new_contest_entry_feedback_path(@contest, @entry)

= render partial: "feedbacks/feedback", collection: @entry.feedbacks