config/routes.rb
Datachimp::Application.routes.draw do
  resources :credit_cards, only: [:index, :new, :create, :destroy]
  resources :bank_accounts, only: [:index, :new, :create, :destroy]
  resources :contest_followings, only: [:index, :create, :destroy]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "contests#index"
  resources :pending_contests, only: [:index]
  resources :past_contests, only: [:index]

  resources :contests do
    resources :entries do
      member do
        post :rate
        delete :remove
        get :pick_winning
      end
      resources :feedbacks, only: [:new, :create, :edit, :update, :destroy]
    end
  end
end

app/models/contest.rb
class Contest < ActiveRecord::Base
  attr_accessible :bounty, :deadline, :description, :name, :user, :winner, :winner_id

  belongs_to :user
  belongs_to :winner, class_name: "Entry", foreign_key: :winner_id
  has_many :entries
  has_many :contest_followings, dependent: :destroy
  has_many :users, through: :contest_followings

  validates :bounty, :deadline, :description, :name, :user, presence: true
  validate :owner_has_account, :on => :create
  before_create :create_bounty
  after_create :follow_contest

  scope :pending, where('winner_id is NULL and deadline > ?', Time.now)
  scope :expired, where('winner_id is not NULL or deadline < ?', Time.now)

  def expired?
    winner.present? || passed_deadline?
  end

  def passed_deadline?
    deadline <= Time.now
  end

  def pick_winner(win_entry)
    return false if self.winner || win_entry.removed
    self.update_attributes(winner: win_entry)
    win_entry.user.credit(bounty * 0.9 * 100)
    return true
  end

  private

  def owner_has_account
    errors.add(:base, "Owner must have a credit card to create a new contest.") unless user.credit_cards.any?
  end

  def create_bounty
    user.charge(bounty * 100)
  end

  def follow_contest
    user.follow(self)
  end
end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_filter :find_contest, only: [:show, :edit, :update, :destroy]
  before_filter :verify_ownership, only: [:update, :destroy]

  # GET /contests
  # GET /contests.json
  def index
    @contests = Contest.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @contests }
    end
  end

  # GET /contests/1
  # GET /contests/1.json
  def show
    flash[:notice] = 'Contest has passed deadline, please choose a winner' if @contest.passed_deadline?
    respond_to do |format|
      format.html
      format.json { render json: @contest }
    end
  end

  # GET /contests/new
  # GET /contests/new.json
  def new
    @contest = Contest.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @contest }
    end
  end

  # GET /contests/1/edit
  def edit
  end

  # POST /contests
  # POST /contests.json
  def create
    @contest = current_user.contests.new(params[:contest])

    respond_to do |format|
      if @contest.save
        format.html { redirect_to @contest, notice: 'Contest was successfully created.' }
        format.json { render json: @contest, status: :created, location: @contest }
      else
        format.html { render action: "new" }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /contests/1
  # PUT /contests/1.json
  def update
    respond_to do |format|
      if @contest.update_attributes(params[:contest].except(:bounty))
        format.html { redirect_to @contest, notice: 'Contest was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contests/1
  # DELETE /contests/1.json
  def destroy
    @contest.destroy

    respond_to do |format|
      format.html { redirect_to contests_url }
      format.json { head :no_content }
    end
  end

  private
  def find_contest
    @contest = Contest.find(params[:id])
  end

  def verify_ownership
    unless current_user == @contest.user
      flash[:notice] = "You do not own this contest"
      redirect_to root_path
      return
    end
  end
end

app/views/contests/_form.html.haml
= form_for @contest do |f|
  - if @contest.errors.any?
    #error_explanation
      %h2= "#{pluralize(@contest.errors.count, "error")} prohibited this contest from being saved:"
      %ul
        - @contest.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :deadline
    = f.datetime_select :deadline, default: 1.day.from_now
  - if @contest.entries.count > 0
    - if @contest.winner
      .field
        = f.label :winner
        = @contest.winner.headline
  .field
    = f.label :bounty
    - if @contest.new_record?
      = f.number_field :bounty
    - else
      = f.number_field :bounty, :disabled => true
  .actions
    = f.submit 'Save'

app/views/contests/edit.html.haml
%h1 Editing contest

= render 'form'

= link_to 'Show', @contest
\|
= link_to 'Back', contests_path

app/views/contests/index.html.haml
%h1 Listing contests

%table
  %tr
    %th Name
    %th Description
    %th Deadline
    %th Winner
    %th Bounty
    %th

  - @contests.each do |contest|
    %tr
      %td= link_to contest.name, contest
      %td= contest.description
      %td= contest.deadline
      %td= contest.winner.user.name if contest.winner
      %td= contest.bounty
      %td
        - if current_user.present?
          - if current_user == contest.user
            = link_to 'Edit', edit_contest_path(contest)
            = link_to 'Destroy', contest, :method => :delete, :data => { :confirm => 'Are you sure?' }
          - else
            - if current_user.following?(contest)
              = link_to 'Unfollow', contest_following_path(current_user.contest_following_for(contest)), method: :delete, :data => { :confirm => 'Are you sure?' }
            - else
              = link_to 'Follow', contest_followings_path(contest_following: { contest_id: contest.id }), method: :post
%br
= link_to 'New Contest', new_contest_path

app/views/contests/new.html.haml
%h1 New contest

= render 'form'

= link_to 'Back', contests_path

app/views/contests/show.html.haml
%p#notice= notice

%p
  %b User:
  = @contest.user.name
%p
  %b Name:
  = @contest.name
%p
  %b Description:
  = @contest.description
%p
  %b Deadline:
  = @contest.deadline
%p
  %b Winner:
  = @contest.winner.user.name if @contest.winner
%p
  %b Bounty:
  = @contest.bounty

- if current_user && current_user.own?(@contest)
  = link_to 'Edit', edit_contest_path(@contest)
  \|
= link_to 'Back', contests_path

%h2 Entries
- unless @contest.expired?
  %p= link_to "Add entry", new_contest_entry_path(@contest)
= render partial: "entries/entry", collection: @contest.entries.active