config/routes.rb
Datachimp::Application.routes.draw do
  resources :credit_cards, only: [:index, :new, :create, :destroy]
  resources :bank_accounts, only: [:index, :new, :create, :destroy]
  resources :contest_followings, only: [:index, :create, :destroy]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "contests#index"
  resources :pending_contests, only: [:index]
  resources :past_contests, only: [:index]

  resources :contests do
    resources :entries do
      member do
        post :rate
        delete :remove
        get :pick_winning
      end
      resources :feedbacks, only: [:new, :create, :edit, :update, :destroy]
    end
  end
end

app/models/credit_card.rb
class CreditCard < BalancedModel
  attr_accessor :card_number, :security_code, :expiration_month, :expiration_year, :uri, :user, :name
  validates :expiration_month, :expiration_year, :card_number, :security_code, :name,  presence: true

  def save
    card = Balanced::Card.new(
      uri: marketplace.cards_uri,
      expiration_month: expiration_month,
      expiration_year: expiration_year,
      security_code: security_code,
      card_number: card_number,
      name: name
    ).save
    balanced_account.add_card(card.uri)
    return true
  rescue Exception => exception
    rescue_with_handler(exception) || raise
    return false
  end

  def destroy
    card = Balanced::Card.find(uri)
    card.invalidate
    return true
  rescue Exception => exception
    rescue_with_handler(exception) || raise
    return false
  end
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @credit_cards = current_user.credit_cards

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @credit_cards }
    end
  end

  def new
    @credit_card = CreditCard.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @credit_card }
    end
  end

  def create
    @credit_card = CreditCard.new(params[:credit_card].merge(user: current_user))

    respond_to do |format|
      if @credit_card.save
        format.html { redirect_to credit_cards_path, notice: 'Credit card was successfully created.' }
        format.json { render json: @credit_card, status: :created, location: @credit_card }
      else
        format.html { render action: "new" }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @credit_card = CreditCard.new(uri: params[:uri])

    respond_to do |format|
      if @credit_card.destroy
        format.html { redirect_to credit_cards_path }
        format.json { head :no_content }
      else
        format.html { redirect_to credit_cards_path, notice: @credit_card.errors.full_messages.first }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/views/credit_cards/_form.html.haml
= form_for @credit_card do |f|
  - if @credit_card.errors.any?
    #error_explanation
      %h2= "#{pluralize(@credit_card.errors.count, "error")} prohibited this credit_card from being saved:"
      %ul
        - @credit_card.errors.full_messages.each do |msg|
          %li= msg
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :card_number
    = f.text_field :card_number
  .field
    = f.label :security_code
    = f.text_field :security_code
  .field
    = f.label :expiration_month
    = f.number_field :expiration_month
  .field
    = f.label :expiration_year
    = f.number_field :expiration_year
  .actions
    = f.submit 'Save'

app/views/credit_cards/index.html.haml
%h1 Listing credit_cards
%table
  %tr
    %th Last four number
    %th Brand
    %th Expiration month
    %th Expiration year
    %th Valid?
    %th
    %th
    %th
  - @credit_cards.each do |credit_card|
    %tr
      %td= credit_card.last_four
      %td= credit_card.brand
      %td= credit_card.expiration_month
      %td= credit_card.expiration_year
      %td= credit_card.is_valid
      %td= link_to 'Destroy', credit_card_path(1, uri: credit_card.uri) , :method => :delete, :data => { :confirm => 'Are you sure?' } if credit_card.is_valid
%br
= link_to 'New Credit card', new_credit_card_path

app/views/credit_cards/new.html.haml
%h1 New credit_card
= render 'form'
= link_to 'Back', credit_cards_path