config/routes.rb
Datachimp::Application.routes.draw do
  resources :credit_cards, only: [:index, :new, :create, :destroy]
  resources :bank_accounts, only: [:index, :new, :create, :destroy]
  resources :contest_followings, only: [:index, :create, :destroy]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "contests#index"
  resources :pending_contests, only: [:index]
  resources :past_contests, only: [:index]

  resources :contests do
    resources :entries do
      member do
        post :rate
        delete :remove
        get :pick_winning
      end
      resources :feedbacks, only: [:new, :create, :edit, :update, :destroy]
    end
  end
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  attr_accessible :content, :entry, :user

  belongs_to :entry
  belongs_to :user

  has_one :contest, through: :entry

  validates :content, presence: true
  validates :user, presence: true
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_contest
  before_filter :find_entry
  before_filter :find_feedback, only: [:update, :destroy]
  before_filter :verify_feedback_ownership, only: [:update, :destroy]
  before_filter :verify_feedback_post_right, only: [:create]

  def new
    @feedback = @entry.feedbacks.new
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = @entry.feedbacks.new(params[:feedback].merge(user: current_user))

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to contest_entry_url(@contest, @entry), notice: 'Feedback was successfully created.' }
        format.json { render json: @feedback, status: :created, location: @feedback }
      else
        format.html { render action: "new" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  # PUT /feedbacks/1
  # PUT /feedbacks/1.json
  def update
    @feedback = Feedback.find(params[:id])

    respond_to do |format|
      if @feedback.update_attributes(params[:feedback])
        format.html { redirect_to contest_entry_url(@contest, @entry), notice: 'Feedback was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy

    respond_to do |format|
      format.html { redirect_to contest_entry_url(@contest, @entry) }
      format.json { head :no_content }
    end
  end
  private
  def find_contest
    @contest = Contest.find(params[:contest_id])
  end

  def find_entry
    @entry = Entry.find(params[:entry_id])
  end

  def find_feedback
    @feedback = Feedback.find(params[:id])
  end

  def verify_feedback_post_right
    unless current_user == @entry.user || current_user == @contest.user
      redirect_to root_path
      return
    end
  end

  def verify_feedback_ownership
    unless current_user == @feedback.user
      redirect_to root_path
      return
    end
  end
end

app/views/feedbacks/_feedback.html.haml
.feedback
  .user
    = feedback.user.name
  .content
    = feedback.content

app/views/feedbacks/_form.html.haml
= form_for [@contest, @entry, @feedback] do |f|
  - if @feedback.errors.any?
    #error_explanation
      %h2= "#{pluralize(@feedback.errors.count, "error")} prohibited this feedback from being saved:"
      %ul
        - @feedback.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :content
    = f.text_area :content
  .actions
    = f.submit 'Save'

app/views/feedbacks/edit.html.haml
%h1 Editing feedback

= render 'form'

= link_to 'Show', contest_entry_feedback_path(@contest, @entry, @feedback)
\|
= link_to 'Back', contest_entry_feedbacks_path(@contest, @entry)

app/views/feedbacks/index.html.haml
%h1 Listing feedbacks

%table
  %tr
    %th Entry
    %th Content
    %th
    %th
    %th

  - @feedbacks.each do |feedback|
    %tr
      %td= feedback.entry_id
      %td= feedback.content
      %td= link_to 'Show', contest_entry_feedback_path(@contest, @entry, feedback)
      %td= link_to 'Edit', edit_contest_entry_feedback_path(@contest, @entry, feedback)
      %td= link_to 'Destroy', contest_entry_feedback_path(@contest, @entry, feedback), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Feedback', new_contest_entry_feedback_path(@contest, @entry)

app/views/feedbacks/new.html.haml
%h1 New feedback

= render 'form'

= link_to 'Back', contest_entry_feedbacks_path(@contest, @entry)

app/views/feedbacks/show.html.haml
%p#notice= notice

%p
  %b Content:
  = @feedback.content

= link_to 'Edit', edit_contest_entry_feedback_path(@contest, @entry, @feedback)
\|
= link_to 'Back', contest_entry_feedbacks_path(@contest, @entry)